apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260626-155117-cjh20n2wfm8i-service
spec:
  selector:
    app: enterprise-system-20260626-155117-cjh20n2wfm8i
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
